aws_message = {
    records : [* aws_record]
}

aws_record = {
    station_wsi: text               ;WIGOS Station Identifier
    obs_dt_utc: int                 ;date and time of observation in UTC units: milliseconds since Epoch
    wind_speed: min_max_block       ;Wind Speed at 10m, Units=knots
    wind_direction: stdev_block     ;Wind Direction at 10m, Units = degrees from magnetic north.
    air_temperature: min_max_block  ;air_temperature at 2m, Units=degrees Celsius
    dew_point: min_max_block        ;dew point temperature at 2m, Units=degrees Celsius
    rel_humidity: min_max_block     ;relative humidity at 2m, Units=%
    visibility: float               ;MOR, Units=m
    rainfall: float                 ;accumulation (resets at 9999.9), Units=mm
    pressure: pressure_block        ;barometric pressure and aviation related derived values, Units=hectopascals
    engineering: engineering_stats  ;data to facilitate engineering support of equipment
    cloud: [* float]                ;height observations from ceilometer, Units=feet
}

min_max_block = {
    average: float                  ;average over the measurement period
    max: float                      ;maximum value in the measurement period
    min: float                      ;minimum value in the measurement period
}

stdev_block = {
    average: float                  ;average over the measurement period
    minus_std_dev: float            ;average value minus standard deviation of observations over measurement period
    plus_std_dev: float             ;average value plus standard deviation of observations over measurement period
}

pressure_block = {
    qfe: float                      ;units=hectopascals
    qff: float                      ;units = hectopascals
    qnh: float                      ;units = hectopascals
}

engineering_stats = {
    battery_voltage: float          ;Output voltage on internal UPS battery, units=V
    internal_temp: float     ;Temperature inside AWS cabinet, units=degrees C
}

