== Data sender

=== Metadata publication
A key feature of the First Mile Format, is the structured inclusion of metadata.  This enables

|===
| Benefit | Definition | Required in implementation
| Machine Translation | Received data can be correctly assigned to observations in database without human interpretation/intervention | Standard Names
| Stranger Interpretation | Siting (particularly location and height of observations) and equipment can be deduced from data, enabling assessment of observation quality without access to other information | Location, URL (for additional information)
| Efficient Communication | Metadata is not included in every message (reducing bandwidth requirements), only to ensure efficient processing by the Receiver| Transmission Triggers
|===


==== Mandatory fields
To enable evolution of the First Mile Standard, while maximising backward compatability, the Protobuf *REQUIRED* keyword is not used.  However, omission of key values can render the other included information unusable as it is ambiguous as to how it is related to the other content.


|===
|Message|Field|Justification
|Node|name|Enables the identification of the end node
|ObserverDevice|id| Enables parameters (observation data) to be matched to the sensing/observing/measuring device
|ParameterDefinition|id|Enables content from Data messages to be interpreted
|Parameter|unit| Critical to hub interpretation of received data
|Parameter|DeviceRef|Enables sensors/observers to be matched  to their data
|===

If machine to machine translation is expected, then the following following additional fields must be included
|===
|Message|Field|Justification
|Parameter|standardNames|Enables machine to machine translation of definition, irrespective of parameter name
|Parameter|CellMethod|If any data processing is done at the edge, this enables for example the mean and standard deviation to be differentiated (as they will have the same standardNames, units)
|===

==== Transmission triggers
The hub is unable to process any Data Messages without a current Metadata Message.

As a minimum, a new/updated Metadata Message must be transmitted whenever the Metadata changes.  This is particularly important when:

* Sensors are added or removed

* New Observations (or statistics on existing observations, for example max/min values) are provided.

To balance network transmission costs for Metadata Messages with impost of storing Data messages until the relevant Metadata message is received and the Data Messages can be understood, recommended practice is (re)sending of the Metadata Message:

* on power-on/restart of hub

* on a "heartbeat" schedule of at least once per day.

==== Retained messages
The Data Messages cannot be understood without their associated Metadata Message.  To meet Archiving requirements footnote:[For Example WMO 1238 (2023) 2.5.5 ] in most jurisdictions the Data Messages, and associated Metadata Messages must both be retained.  Typically, this can be a one (Metadata Message) to many (Data Messages) relationship

== Data publication
The First Mile Format enables efficient communication of Data:

* the message is a compact/efficient binary format.
* only the Observation/Data values are transmitted [as the less often transmitted Metadata Message carries the information to understand the values]

==== Mandatory fields
Every Data message must contain at least:

|===
|parameterDefinitionId | Enables the Data to be matched to the definition from the Metadata Message
|time|
| (at least one) value |
|===


==== Observation timestamps
The Data (Observation) Timestamp uses the google.protobuf.Timestamp structure for each observation.

----
message Timestamp {
    int64 seconds = 1; // Seconds since UTC (Unix) epoch (1/1/1970)
    int32 nanos = 2; // non-negative nanosecond fractions
}
----

The structure enables date/time resolutions to nanoseconds for observations.

=== Device identification
The Data Message does not contain any Station/Device information in the message.  Instead, the MQTT topic hierarchy NodeID (Level 4) would be used for Station/Device Identification and should be archived with the Data Message.