/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_WMO_FIRSTMILE_POC1_FIRSTMILE_PB_H_INCLUDED
#define PB_WMO_FIRSTMILE_POC1_FIRSTMILE_PB_H_INCLUDED
#include <pb.h>
#include "google/protobuf/empty.pb.h"
#include "google/protobuf/timestamp.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _wmo_firstmile_poc1_CellMethod {
    wmo_firstmile_poc1_CellMethod_CELL_METHOD_UNSPECIFIED = 0, /* Required default */
    wmo_firstmile_poc1_CellMethod_POINT = 1, /* Instantaneous value at a point */
    wmo_firstmile_poc1_CellMethod_SUM = 2, /* Sum over the cell */
    wmo_firstmile_poc1_CellMethod_MAXIMUM = 3, /* Maximum value */
    wmo_firstmile_poc1_CellMethod_MAXIMUM_ABSOLUTE_VALUE = 4, /* Maximum of absolute values */
    wmo_firstmile_poc1_CellMethod_MEDIAN = 5, /* Median value */
    wmo_firstmile_poc1_CellMethod_MID_RANGE = 6, /* Average of maximum and minimum */
    wmo_firstmile_poc1_CellMethod_MINIMUM = 7, /* Minimum value */
    wmo_firstmile_poc1_CellMethod_MINIMUM_ABSOLUTE_VALUE = 8, /* Minimum of absolute values */
    wmo_firstmile_poc1_CellMethod_MEAN = 9, /* Mean (average) value */
    wmo_firstmile_poc1_CellMethod_MEAN_ABSOLUTE_VALUE = 10, /* Mean of absolute values */
    wmo_firstmile_poc1_CellMethod_MEAN_OF_UPPER_DECILE = 11, /* Mean of the upper group of data values defined by the upper tenth of their distribution */
    wmo_firstmile_poc1_CellMethod_MODE = 12, /* Mode (most common value) */
    wmo_firstmile_poc1_CellMethod_RANGE = 13, /* Absolute difference between maximum and minimum */
    wmo_firstmile_poc1_CellMethod_ROOT_MEAN_SQUARE = 14, /* Root mean square (RMS) */
    wmo_firstmile_poc1_CellMethod_STANDARD_DEVIATION = 15, /* Standard deviation within the cell */
    wmo_firstmile_poc1_CellMethod_SUM_OF_SQUARES = 16, /* Sum of squares */
    wmo_firstmile_poc1_CellMethod_VARIANCE = 17 /* Variance within the cell */
} wmo_firstmile_poc1_CellMethod;

typedef enum _wmo_firstmile_poc1_ReferenceSurface {
    wmo_firstmile_poc1_ReferenceSurface_REFERENCE_SURFACE_UNSPECIFIED = 0, /* Default */
    wmo_firstmile_poc1_ReferenceSurface_MSL = 1, /* Mean Sea Level */
    wmo_firstmile_poc1_ReferenceSurface_GEOID = 2, /* Geoid */
    wmo_firstmile_poc1_ReferenceSurface_GL = 3, /* Ground Level */
    wmo_firstmile_poc1_ReferenceSurface_REFERENCE_ELLIPSOID = 4, /* Reference Ellipsoid */
    wmo_firstmile_poc1_ReferenceSurface_PRESSURE_1000_HPA = 5 /* 1000 hPa Pressure Level */
} wmo_firstmile_poc1_ReferenceSurface;

/* Struct definitions */
typedef struct _wmo_firstmile_poc1_DeviceRef {
    pb_size_t which_target;
    union _wmo_firstmile_poc1_DeviceRef_target {
        google_protobuf_Empty host; /* if field is present => refers to the single host */
        uint32_t observerId;
    } target;
} wmo_firstmile_poc1_DeviceRef;

typedef struct _wmo_firstmile_poc1_Parameter {
    pb_callback_t longName;
    pb_callback_t unit;
    pb_callback_t standardNames;
    bool has_device;
    wmo_firstmile_poc1_DeviceRef device;
    wmo_firstmile_poc1_CellMethod cellMethod;
    uint32_t cellPeriodSeconds;
} wmo_firstmile_poc1_Parameter;

typedef struct _wmo_firstmile_poc1_Parameter_StandardNamesEntry {
    pb_callback_t key;
    pb_callback_t value;
} wmo_firstmile_poc1_Parameter_StandardNamesEntry;

typedef struct _wmo_firstmile_poc1_ParameterDefinition {
    uint32_t id;
    pb_callback_t description;
    pb_callback_t parameters;
} wmo_firstmile_poc1_ParameterDefinition;

typedef struct _wmo_firstmile_poc1_Value {
    pb_size_t which_kind;
    union _wmo_firstmile_poc1_Value_kind {
        float floatValue;
        double doubleValue;
        int32_t intValue;
        uint32_t unsignedIntValue;
        int64_t int64Value;
        uint64_t unsignedInt64Value;
        pb_callback_t stringValue;
        bool boolValue;
        google_protobuf_Empty emptyValue;
    } kind;
} wmo_firstmile_poc1_Value;

typedef struct _wmo_firstmile_poc1_Observation {
    uint32_t parameterDefinitionId;
    bool has_time;
    google_protobuf_Timestamp time;
    pb_callback_t values;
} wmo_firstmile_poc1_Observation;

typedef struct _wmo_firstmile_poc1_Location {
    bool has_latitude;
    double latitude;
    bool has_longitude;
    double longitude;
    double heightMeter;
    wmo_firstmile_poc1_ReferenceSurface referenceSurface;
} wmo_firstmile_poc1_Location;

typedef struct _wmo_firstmile_poc1_HostDevice {
    pb_callback_t name;
    bool has_location;
    wmo_firstmile_poc1_Location location;
    pb_callback_t url;
    pb_callback_t serialNumber;
    pb_callback_t firmwareVersion;
} wmo_firstmile_poc1_HostDevice;

typedef struct _wmo_firstmile_poc1_ObserverDevice {
    uint32_t id;
    pb_callback_t name;
    bool has_location;
    wmo_firstmile_poc1_Location location;
    pb_callback_t url;
    pb_callback_t serialNumber;
    pb_callback_t firmwareVersion;
} wmo_firstmile_poc1_ObserverDevice;

typedef struct _wmo_firstmile_poc1_Data {
    pb_callback_t observations;
} wmo_firstmile_poc1_Data;

typedef struct _wmo_firstmile_poc1_Metadata {
    bool has_host;
    wmo_firstmile_poc1_HostDevice host;
    pb_callback_t observers;
    pb_callback_t parameterDefinitions;
    pb_callback_t namespaces;
} wmo_firstmile_poc1_Metadata;

typedef struct _wmo_firstmile_poc1_Metadata_NamespacesEntry {
    pb_callback_t key;
    pb_callback_t value;
} wmo_firstmile_poc1_Metadata_NamespacesEntry;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _wmo_firstmile_poc1_CellMethod_MIN wmo_firstmile_poc1_CellMethod_CELL_METHOD_UNSPECIFIED
#define _wmo_firstmile_poc1_CellMethod_MAX wmo_firstmile_poc1_CellMethod_VARIANCE
#define _wmo_firstmile_poc1_CellMethod_ARRAYSIZE ((wmo_firstmile_poc1_CellMethod)(wmo_firstmile_poc1_CellMethod_VARIANCE+1))

#define _wmo_firstmile_poc1_ReferenceSurface_MIN wmo_firstmile_poc1_ReferenceSurface_REFERENCE_SURFACE_UNSPECIFIED
#define _wmo_firstmile_poc1_ReferenceSurface_MAX wmo_firstmile_poc1_ReferenceSurface_PRESSURE_1000_HPA
#define _wmo_firstmile_poc1_ReferenceSurface_ARRAYSIZE ((wmo_firstmile_poc1_ReferenceSurface)(wmo_firstmile_poc1_ReferenceSurface_PRESSURE_1000_HPA+1))


#define wmo_firstmile_poc1_Parameter_cellMethod_ENUMTYPE wmo_firstmile_poc1_CellMethod





#define wmo_firstmile_poc1_Location_referenceSurface_ENUMTYPE wmo_firstmile_poc1_ReferenceSurface







/* Initializer values for message structs */
#define wmo_firstmile_poc1_DeviceRef_init_default {0, {google_protobuf_Empty_init_default}}
#define wmo_firstmile_poc1_Parameter_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, wmo_firstmile_poc1_DeviceRef_init_default, _wmo_firstmile_poc1_CellMethod_MIN, 0}
#define wmo_firstmile_poc1_Parameter_StandardNamesEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define wmo_firstmile_poc1_ParameterDefinition_init_default {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define wmo_firstmile_poc1_Value_init_default    {0, {0}}
#define wmo_firstmile_poc1_Observation_init_default {0, false, google_protobuf_Timestamp_init_default, {{NULL}, NULL}}
#define wmo_firstmile_poc1_Location_init_default {false, 0, false, 0, 0, _wmo_firstmile_poc1_ReferenceSurface_MIN}
#define wmo_firstmile_poc1_HostDevice_init_default {{{NULL}, NULL}, false, wmo_firstmile_poc1_Location_init_default, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define wmo_firstmile_poc1_ObserverDevice_init_default {0, {{NULL}, NULL}, false, wmo_firstmile_poc1_Location_init_default, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define wmo_firstmile_poc1_Data_init_default     {{{NULL}, NULL}}
#define wmo_firstmile_poc1_Metadata_init_default {false, wmo_firstmile_poc1_HostDevice_init_default, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define wmo_firstmile_poc1_Metadata_NamespacesEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define wmo_firstmile_poc1_DeviceRef_init_zero   {0, {google_protobuf_Empty_init_zero}}
#define wmo_firstmile_poc1_Parameter_init_zero   {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, wmo_firstmile_poc1_DeviceRef_init_zero, _wmo_firstmile_poc1_CellMethod_MIN, 0}
#define wmo_firstmile_poc1_Parameter_StandardNamesEntry_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define wmo_firstmile_poc1_ParameterDefinition_init_zero {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define wmo_firstmile_poc1_Value_init_zero       {0, {0}}
#define wmo_firstmile_poc1_Observation_init_zero {0, false, google_protobuf_Timestamp_init_zero, {{NULL}, NULL}}
#define wmo_firstmile_poc1_Location_init_zero    {false, 0, false, 0, 0, _wmo_firstmile_poc1_ReferenceSurface_MIN}
#define wmo_firstmile_poc1_HostDevice_init_zero  {{{NULL}, NULL}, false, wmo_firstmile_poc1_Location_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define wmo_firstmile_poc1_ObserverDevice_init_zero {0, {{NULL}, NULL}, false, wmo_firstmile_poc1_Location_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define wmo_firstmile_poc1_Data_init_zero        {{{NULL}, NULL}}
#define wmo_firstmile_poc1_Metadata_init_zero    {false, wmo_firstmile_poc1_HostDevice_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define wmo_firstmile_poc1_Metadata_NamespacesEntry_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define wmo_firstmile_poc1_DeviceRef_host_tag    1
#define wmo_firstmile_poc1_DeviceRef_observerId_tag 2
#define wmo_firstmile_poc1_Parameter_longName_tag 1
#define wmo_firstmile_poc1_Parameter_unit_tag    2
#define wmo_firstmile_poc1_Parameter_standardNames_tag 3
#define wmo_firstmile_poc1_Parameter_device_tag  4
#define wmo_firstmile_poc1_Parameter_cellMethod_tag 5
#define wmo_firstmile_poc1_Parameter_cellPeriodSeconds_tag 6
#define wmo_firstmile_poc1_Parameter_StandardNamesEntry_key_tag 1
#define wmo_firstmile_poc1_Parameter_StandardNamesEntry_value_tag 2
#define wmo_firstmile_poc1_ParameterDefinition_id_tag 1
#define wmo_firstmile_poc1_ParameterDefinition_description_tag 2
#define wmo_firstmile_poc1_ParameterDefinition_parameters_tag 3
#define wmo_firstmile_poc1_Value_floatValue_tag  1
#define wmo_firstmile_poc1_Value_doubleValue_tag 2
#define wmo_firstmile_poc1_Value_intValue_tag    3
#define wmo_firstmile_poc1_Value_unsignedIntValue_tag 4
#define wmo_firstmile_poc1_Value_int64Value_tag  5
#define wmo_firstmile_poc1_Value_unsignedInt64Value_tag 6
#define wmo_firstmile_poc1_Value_stringValue_tag 7
#define wmo_firstmile_poc1_Value_boolValue_tag   8
#define wmo_firstmile_poc1_Value_emptyValue_tag  9
#define wmo_firstmile_poc1_Observation_parameterDefinitionId_tag 1
#define wmo_firstmile_poc1_Observation_time_tag  2
#define wmo_firstmile_poc1_Observation_values_tag 3
#define wmo_firstmile_poc1_Location_latitude_tag 1
#define wmo_firstmile_poc1_Location_longitude_tag 2
#define wmo_firstmile_poc1_Location_heightMeter_tag 3
#define wmo_firstmile_poc1_Location_referenceSurface_tag 4
#define wmo_firstmile_poc1_HostDevice_name_tag   1
#define wmo_firstmile_poc1_HostDevice_location_tag 2
#define wmo_firstmile_poc1_HostDevice_url_tag    3
#define wmo_firstmile_poc1_HostDevice_serialNumber_tag 4
#define wmo_firstmile_poc1_HostDevice_firmwareVersion_tag 5
#define wmo_firstmile_poc1_ObserverDevice_id_tag 1
#define wmo_firstmile_poc1_ObserverDevice_name_tag 2
#define wmo_firstmile_poc1_ObserverDevice_location_tag 3
#define wmo_firstmile_poc1_ObserverDevice_url_tag 4
#define wmo_firstmile_poc1_ObserverDevice_serialNumber_tag 5
#define wmo_firstmile_poc1_ObserverDevice_firmwareVersion_tag 6
#define wmo_firstmile_poc1_Data_observations_tag 1
#define wmo_firstmile_poc1_Metadata_host_tag     1
#define wmo_firstmile_poc1_Metadata_observers_tag 2
#define wmo_firstmile_poc1_Metadata_parameterDefinitions_tag 3
#define wmo_firstmile_poc1_Metadata_namespaces_tag 4
#define wmo_firstmile_poc1_Metadata_NamespacesEntry_key_tag 1
#define wmo_firstmile_poc1_Metadata_NamespacesEntry_value_tag 2

/* Struct field encoding specification for nanopb */
#define wmo_firstmile_poc1_DeviceRef_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (target,host,target.host),   1) \
X(a, STATIC,   ONEOF,    UINT32,   (target,observerId,target.observerId),   2)
#define wmo_firstmile_poc1_DeviceRef_CALLBACK NULL
#define wmo_firstmile_poc1_DeviceRef_DEFAULT NULL
#define wmo_firstmile_poc1_DeviceRef_target_host_MSGTYPE google_protobuf_Empty

#define wmo_firstmile_poc1_Parameter_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   longName,          1) \
X(a, CALLBACK, SINGULAR, STRING,   unit,              2) \
X(a, CALLBACK, REPEATED, MESSAGE,  standardNames,     3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device,            4) \
X(a, STATIC,   SINGULAR, UENUM,    cellMethod,        5) \
X(a, STATIC,   SINGULAR, UINT32,   cellPeriodSeconds,   6)
#define wmo_firstmile_poc1_Parameter_CALLBACK pb_default_field_callback
#define wmo_firstmile_poc1_Parameter_DEFAULT NULL
#define wmo_firstmile_poc1_Parameter_standardNames_MSGTYPE wmo_firstmile_poc1_Parameter_StandardNamesEntry
#define wmo_firstmile_poc1_Parameter_device_MSGTYPE wmo_firstmile_poc1_DeviceRef

#define wmo_firstmile_poc1_Parameter_StandardNamesEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define wmo_firstmile_poc1_Parameter_StandardNamesEntry_CALLBACK pb_default_field_callback
#define wmo_firstmile_poc1_Parameter_StandardNamesEntry_DEFAULT NULL

#define wmo_firstmile_poc1_ParameterDefinition_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, CALLBACK, SINGULAR, STRING,   description,       2) \
X(a, CALLBACK, REPEATED, MESSAGE,  parameters,        3)
#define wmo_firstmile_poc1_ParameterDefinition_CALLBACK pb_default_field_callback
#define wmo_firstmile_poc1_ParameterDefinition_DEFAULT NULL
#define wmo_firstmile_poc1_ParameterDefinition_parameters_MSGTYPE wmo_firstmile_poc1_Parameter

#define wmo_firstmile_poc1_Value_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    FLOAT,    (kind,floatValue,kind.floatValue),   1) \
X(a, STATIC,   ONEOF,    DOUBLE,   (kind,doubleValue,kind.doubleValue),   2) \
X(a, STATIC,   ONEOF,    INT32,    (kind,intValue,kind.intValue),   3) \
X(a, STATIC,   ONEOF,    UINT32,   (kind,unsignedIntValue,kind.unsignedIntValue),   4) \
X(a, STATIC,   ONEOF,    INT64,    (kind,int64Value,kind.int64Value),   5) \
X(a, STATIC,   ONEOF,    UINT64,   (kind,unsignedInt64Value,kind.unsignedInt64Value),   6) \
X(a, CALLBACK, ONEOF,    STRING,   (kind,stringValue,kind.stringValue),   7) \
X(a, STATIC,   ONEOF,    BOOL,     (kind,boolValue,kind.boolValue),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,emptyValue,kind.emptyValue),   9)
#define wmo_firstmile_poc1_Value_CALLBACK pb_default_field_callback
#define wmo_firstmile_poc1_Value_DEFAULT NULL
#define wmo_firstmile_poc1_Value_kind_emptyValue_MSGTYPE google_protobuf_Empty

#define wmo_firstmile_poc1_Observation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   parameterDefinitionId,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  time,              2) \
X(a, CALLBACK, REPEATED, MESSAGE,  values,            3)
#define wmo_firstmile_poc1_Observation_CALLBACK pb_default_field_callback
#define wmo_firstmile_poc1_Observation_DEFAULT NULL
#define wmo_firstmile_poc1_Observation_time_MSGTYPE google_protobuf_Timestamp
#define wmo_firstmile_poc1_Observation_values_MSGTYPE wmo_firstmile_poc1_Value

#define wmo_firstmile_poc1_Location_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, DOUBLE,   latitude,          1) \
X(a, STATIC,   OPTIONAL, DOUBLE,   longitude,         2) \
X(a, STATIC,   SINGULAR, DOUBLE,   heightMeter,       3) \
X(a, STATIC,   SINGULAR, UENUM,    referenceSurface,   4)
#define wmo_firstmile_poc1_Location_CALLBACK NULL
#define wmo_firstmile_poc1_Location_DEFAULT NULL

#define wmo_firstmile_poc1_HostDevice_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  location,          2) \
X(a, CALLBACK, OPTIONAL, STRING,   url,               3) \
X(a, CALLBACK, OPTIONAL, STRING,   serialNumber,      4) \
X(a, CALLBACK, OPTIONAL, STRING,   firmwareVersion,   5)
#define wmo_firstmile_poc1_HostDevice_CALLBACK pb_default_field_callback
#define wmo_firstmile_poc1_HostDevice_DEFAULT NULL
#define wmo_firstmile_poc1_HostDevice_location_MSGTYPE wmo_firstmile_poc1_Location

#define wmo_firstmile_poc1_ObserverDevice_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, CALLBACK, SINGULAR, STRING,   name,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  location,          3) \
X(a, CALLBACK, OPTIONAL, STRING,   url,               4) \
X(a, CALLBACK, OPTIONAL, STRING,   serialNumber,      5) \
X(a, CALLBACK, OPTIONAL, STRING,   firmwareVersion,   6)
#define wmo_firstmile_poc1_ObserverDevice_CALLBACK pb_default_field_callback
#define wmo_firstmile_poc1_ObserverDevice_DEFAULT NULL
#define wmo_firstmile_poc1_ObserverDevice_location_MSGTYPE wmo_firstmile_poc1_Location

#define wmo_firstmile_poc1_Data_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  observations,      1)
#define wmo_firstmile_poc1_Data_CALLBACK pb_default_field_callback
#define wmo_firstmile_poc1_Data_DEFAULT NULL
#define wmo_firstmile_poc1_Data_observations_MSGTYPE wmo_firstmile_poc1_Observation

#define wmo_firstmile_poc1_Metadata_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  host,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  observers,         2) \
X(a, CALLBACK, REPEATED, MESSAGE,  parameterDefinitions,   3) \
X(a, CALLBACK, REPEATED, MESSAGE,  namespaces,        4)
#define wmo_firstmile_poc1_Metadata_CALLBACK pb_default_field_callback
#define wmo_firstmile_poc1_Metadata_DEFAULT NULL
#define wmo_firstmile_poc1_Metadata_host_MSGTYPE wmo_firstmile_poc1_HostDevice
#define wmo_firstmile_poc1_Metadata_observers_MSGTYPE wmo_firstmile_poc1_ObserverDevice
#define wmo_firstmile_poc1_Metadata_parameterDefinitions_MSGTYPE wmo_firstmile_poc1_ParameterDefinition
#define wmo_firstmile_poc1_Metadata_namespaces_MSGTYPE wmo_firstmile_poc1_Metadata_NamespacesEntry

#define wmo_firstmile_poc1_Metadata_NamespacesEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define wmo_firstmile_poc1_Metadata_NamespacesEntry_CALLBACK pb_default_field_callback
#define wmo_firstmile_poc1_Metadata_NamespacesEntry_DEFAULT NULL

extern const pb_msgdesc_t wmo_firstmile_poc1_DeviceRef_msg;
extern const pb_msgdesc_t wmo_firstmile_poc1_Parameter_msg;
extern const pb_msgdesc_t wmo_firstmile_poc1_Parameter_StandardNamesEntry_msg;
extern const pb_msgdesc_t wmo_firstmile_poc1_ParameterDefinition_msg;
extern const pb_msgdesc_t wmo_firstmile_poc1_Value_msg;
extern const pb_msgdesc_t wmo_firstmile_poc1_Observation_msg;
extern const pb_msgdesc_t wmo_firstmile_poc1_Location_msg;
extern const pb_msgdesc_t wmo_firstmile_poc1_HostDevice_msg;
extern const pb_msgdesc_t wmo_firstmile_poc1_ObserverDevice_msg;
extern const pb_msgdesc_t wmo_firstmile_poc1_Data_msg;
extern const pb_msgdesc_t wmo_firstmile_poc1_Metadata_msg;
extern const pb_msgdesc_t wmo_firstmile_poc1_Metadata_NamespacesEntry_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define wmo_firstmile_poc1_DeviceRef_fields &wmo_firstmile_poc1_DeviceRef_msg
#define wmo_firstmile_poc1_Parameter_fields &wmo_firstmile_poc1_Parameter_msg
#define wmo_firstmile_poc1_Parameter_StandardNamesEntry_fields &wmo_firstmile_poc1_Parameter_StandardNamesEntry_msg
#define wmo_firstmile_poc1_ParameterDefinition_fields &wmo_firstmile_poc1_ParameterDefinition_msg
#define wmo_firstmile_poc1_Value_fields &wmo_firstmile_poc1_Value_msg
#define wmo_firstmile_poc1_Observation_fields &wmo_firstmile_poc1_Observation_msg
#define wmo_firstmile_poc1_Location_fields &wmo_firstmile_poc1_Location_msg
#define wmo_firstmile_poc1_HostDevice_fields &wmo_firstmile_poc1_HostDevice_msg
#define wmo_firstmile_poc1_ObserverDevice_fields &wmo_firstmile_poc1_ObserverDevice_msg
#define wmo_firstmile_poc1_Data_fields &wmo_firstmile_poc1_Data_msg
#define wmo_firstmile_poc1_Metadata_fields &wmo_firstmile_poc1_Metadata_msg
#define wmo_firstmile_poc1_Metadata_NamespacesEntry_fields &wmo_firstmile_poc1_Metadata_NamespacesEntry_msg

/* Maximum encoded size of messages (where known) */
/* wmo_firstmile_poc1_Parameter_size depends on runtime parameters */
/* wmo_firstmile_poc1_Parameter_StandardNamesEntry_size depends on runtime parameters */
/* wmo_firstmile_poc1_ParameterDefinition_size depends on runtime parameters */
/* wmo_firstmile_poc1_Value_size depends on runtime parameters */
/* wmo_firstmile_poc1_Observation_size depends on runtime parameters */
/* wmo_firstmile_poc1_HostDevice_size depends on runtime parameters */
/* wmo_firstmile_poc1_ObserverDevice_size depends on runtime parameters */
/* wmo_firstmile_poc1_Data_size depends on runtime parameters */
/* wmo_firstmile_poc1_Metadata_size depends on runtime parameters */
/* wmo_firstmile_poc1_Metadata_NamespacesEntry_size depends on runtime parameters */
#define WMO_FIRSTMILE_POC1_FIRSTMILE_PB_H_MAX_SIZE wmo_firstmile_poc1_Location_size
#define wmo_firstmile_poc1_DeviceRef_size        6
#define wmo_firstmile_poc1_Location_size         29

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
