/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "firstmile.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(wmo_firstmile_poc1_DeviceRef, wmo_firstmile_poc1_DeviceRef, AUTO)


PB_BIND(wmo_firstmile_poc1_Parameter, wmo_firstmile_poc1_Parameter, AUTO)


PB_BIND(wmo_firstmile_poc1_Parameter_StandardNamesEntry, wmo_firstmile_poc1_Parameter_StandardNamesEntry, AUTO)


PB_BIND(wmo_firstmile_poc1_ParameterDefinition, wmo_firstmile_poc1_ParameterDefinition, AUTO)


PB_BIND(wmo_firstmile_poc1_Value, wmo_firstmile_poc1_Value, AUTO)


PB_BIND(wmo_firstmile_poc1_Observation, wmo_firstmile_poc1_Observation, AUTO)


PB_BIND(wmo_firstmile_poc1_Location, wmo_firstmile_poc1_Location, AUTO)


PB_BIND(wmo_firstmile_poc1_HostDevice, wmo_firstmile_poc1_HostDevice, AUTO)


PB_BIND(wmo_firstmile_poc1_ObserverDevice, wmo_firstmile_poc1_ObserverDevice, AUTO)


PB_BIND(wmo_firstmile_poc1_Data, wmo_firstmile_poc1_Data, AUTO)


PB_BIND(wmo_firstmile_poc1_Metadata, wmo_firstmile_poc1_Metadata, AUTO)


PB_BIND(wmo_firstmile_poc1_Metadata_NamespacesEntry, wmo_firstmile_poc1_Metadata_NamespacesEntry, AUTO)







#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

