name: Test WMO First Mile Data Collection Guide

on:
  pull_request:
    paths:
      - '**.adoc'   
      
env:
  FILE_BASENAME: first-mile-guide-DRAFT

jobs:
  build-first-mile-guide:
    name: Test documentation build
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -y \
          && sudo apt-get install -y pandoc \
          && sudo gem install asciidoctor asciidoctor-pdf
      - name: checkout repository
        uses: actions/checkout@master
      - name: build documentation
        run: |
          cd first-mile-guide \
          && asciidoctor --trace -o /tmp/first-mile-guide/first-mile-guide/${FILE_BASENAME}.html index.adoc \
          && asciidoctor -a allow-uri-read --trace --backend docbook --out-file - index.adoc | pandoc --from docbook --to docx --output /tmp/first-mile-guide/first-mile-guide/${FILE_BASENAME}.docx \
          && asciidoctor -a allow-uri-read --trace -r asciidoctor-pdf --trace -b pdf -o /tmp/first-mile-guide/first-mile-guide/${FILE_BASENAME}.pdf index.adoc
